Tsukada
WebYorozuya/jazz-review pull request #294
Opened 2020-10-17 13:35 UTC by tuka1031

#268 ユーザーメニュー周りのデザイン統一
home.blade.phpとHomeController.phpをMypageに名前変更
logoutを実装

2020-10-17 14:27 UTC, kakudaisuke requested changes
数点見直しをよろしくお願いします！！

2020-10-17 14:27 UTC, kakudaisuke commented on app/Http/Controllers/UserController.php
> +        return redirect()->route('login');
ログアウトしたらloginページに遷移させようとしていますか？トップページの方がいいような？

2020-10-17 14:27 UTC, kakudaisuke commented on resources/views/components/header.blade.php
> +      <form class="header-search" action="cgi-bin/example.cgi" method="post">
むむ。ちょっとファイルが古いかも？？汗
最新はこうなっているのです。 <form class="header-search" action="{{ url('/search')}}" method="get">

2020-10-17 14:27 UTC, kakudaisuke commented on resources/views/components/header.blade.php
>  <header>
このheader.blade.phpは全体が書き換えられようとしているので、少し注意が必要ですね。。

2020-10-17 14:29 UTC, tuka1031 commented on app/Http/Controllers/UserController.php
> +        return redirect()->route('login');
なぜかindex指定できなかったんですよね・・・

2020-10-17 14:29 UTC, tuka1031 commented on resources/views/components/header.blade.php
>  <header>
？？？
私は、どうしたらいいんですか？

2020-10-17 14:31 UTC, tuka1031 commented on resources/views/components/header.blade.php
> +      <form class="header-search" action="cgi-bin/example.cgi" method="post">
書き換えてもう一度pushすればいいですか？

2020-10-18 09:54 UTC, kakudaisuke commented on app/Http/Controllers/UserController.php
> +        return redirect()->route('login');
/  じゃダメでしょうかね？

2020-10-18 10:00 UTC, kakudaisuke commented on resources/views/components/header.blade.php
> +      <form class="header-search" action="cgi-bin/example.cgi" method="post">
ですね。３点目の指摘とも関連しますが、他の箇所も今回の更新以外で、masterと違いがないか確認したいところです。
全行目視で確認するのは面倒なので、一度ローカルでdevelopをpull/mergeする。
- そのためにまずourblade.blade.phpをローカルかどこかにコピーを作って逃しておく。
- pull/mergeして、何も問題起きなければそのままpush。
- コンフリクト起きたり、元々つかちゃんが意図したプログラムになっていなければ、ローカルに逃しておいたコピーを見ながら再度必要な箇所だけ変更する。

これがいいかなと思います。

2020-10-18 10:01 UTC, kakudaisuke commented on resources/views/components/header.blade.php
>  <header>
上のリプライをご参照ください！わからなければ電話してください！

2020-10-18 10:03 UTC, tuka1031 commented on app/Http/Controllers/UserController.php
> +        return redirect()->route('login');
やってみたのですが、ダメでした。

2020-10-18 10:04 UTC, tuka1031 commented on resources/views/components/header.blade.php
> +      <form class="header-search" action="cgi-bin/example.cgi" method="post">
ちょっと不安なので、画面共有しながらやりたいです。
明日、時間ある時一緒にお願いしたいです。

2020-10-18 11:47 UTC, kakudaisuke commented on resources/views/components/header.blade.php
> +      <form class="header-search" action="cgi-bin/example.cgi" method="post">
オッケーです！

2020-10-19 05:31 UTC, merged