Waito
WebYorozuya/jazz-review pull request #330
Opened 2020-10-25 17:22 UTC by uekiGityuto

検索フォームのレスポンシブ対応

2020-10-26 11:57 UTC, kakudaisuke requested changes

2020-10-26 11:57 UTC, kakudaisuke commented on resources/views/components/header.blade.php
>  <header>
@uekiGityuto このファイルってインデント４つになったりしてませんか？？

2020-10-26 14:17 UTC, uekiGityuto commented on resources/views/components/header.blade.php
>  <header>
多分なっています！2個でしたっけ？

2020-10-27 07:45 UTC, kakudaisuke commented on resources/views/components/header.blade.php
>  <header>
はい、２個でお願いします！

2020-10-27 09:01 UTC, uekiGityuto commented on resources/views/components/header.blade.php
>  <header>
直しました。確認お願いします。
（インデント直した後、developの最新を取り込んだので、コミット履歴が2個ありますが、
　「インデント修正」が指摘対応したものです）

2020-10-27 09:12 UTC, kakudaisuke approved these changes

2020-10-27 09:12 UTC, kakudaisuke commented on resources/views/components/header.blade.php
>  <header>
ありがとうございます！！

2020-10-27 09:12 UTC, merged